import React from 'react';
import Select from '../ui/Select';
import Input from '../ui/Input';
import { User } from 'lucide-react';

const StepOne = ({ formData, handleChange }) => {
  return (
    <div className="space-y-8">
      {/* Photo & Basic Info Row */}
      <div className="flex flex-col md:flex-row gap-8">
        {/* Passport Placeholder */}
        <label htmlFor='upload' className="w-32 cursor-pointer hover:bg-gray-200 h-40 bg-gray-100 border-2 border-dashed border-gray-300 rounded-lg flex flex-col items-center justify-center text-center p-2">
          <span className="text-2xl mb-2"><User size={32} /></span>
          <span className="text-[10px] uppercase font-bold text-gray-400">Upload Photo</span>
        </label>

        <input type='file' className='border hidden' id='upload' />

        <div className="flex-1 grid grid-cols-1 md:grid-cols-2 gap-4">
          <Input 
            label="Patient ID (PID)" 
            name="pid" 
            value={formData.pid} 
            onChange={handleChange} 
            required 
          />
          <Select 
            label="Civil Status" 
            name="civilStatus" 
            value={formData.civilStatus} 
            onChange={handleChange}
            options={[
              {value:"single", label:"Single"},
              {value:"married", label:"Married"},
              {value:"divorced", label:"Divorced"},
              {value:"widowed", label:"Widowed"},
              {value:"separated", label:"Separated"}
            ]}
            required 
          />
        </div>
      </div>

      {/* Name Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Input 
          label="Last Name" 
          name="lastName" 
          placeholder="e.g Lasisi" 
          value={formData.lastName} 
          onChange={handleChange} 
          required 
        />
        <Input 
          label="First Name" 
          name="firstName" 
          placeholder="e.g. John" 
          value={formData.firstName} 
          onChange={handleChange} 
          required 
        />
        <Input 
          label="Other Names" 
          name="otherNames" 
          placeholder="e.g. Adaeze" 
          value={formData.otherNames} 
          onChange={handleChange} 
        />
      </div>

      {/* Demographic Grid */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Input
          label="Date of Birth" 
          name="dob" 
          type="date" 
          value={formData.dob} 
          onChange={handleChange} 
          required 
        />
        <Input
          label="Age" 
          name="age" 
          value={formData.age} 
          onChange={handleChange} 
          placeholder="Calculated from DOB"
          readOnly // since the age is autogenerated from DOB, users do not need to edit it
        />
        <Select 
          label="Gender" 
          name="gender" 
          value={formData.gender} 
          onChange={handleChange} 
          options={[
            {value:"male", label:"Male"},
            {value:"female", label:"Female"},
            {value:"other", label:"Other"}
          ]}
          required 
        />
        <Input 
          label="Nationality" 
          name="nationality" 
          value={formData.nationality} 
          onChange={handleChange} 
        />
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <Input 
          label="Tribe" 
          name="tribe" 
          placeholder="e.g. Yoruba" 
          value={formData.tribe} 
          onChange={handleChange} 
        />
        <Select 
          label="Religion" 
          name="religion" 
          value={formData.religion} 
          onChange={handleChange} 
          options={[
            {value:"christianity", label:"Christianity"},
            {value:"islam", label:"Islam"},
            {value:"traditional", label:"Traditional"},
            {value:"other", label:"Other"}
          ]}
        />
      </div>
    </div>
  );
};

export default StepOne;